########################### SpaceVim选项 ###########################
[options]
    # neovim基础配置
    # 默认的gruvbox主题在core-layer
    # inoremap jk 定义在default.vim
    # vimcompatible = true
    wildignore = true
    default_indent = 4
    enable_guicolors = true
    # colorscheme = "default"
    # guifont = 'Source Code Pro Black:10:i'

    # statusline和tabline配置
    statusline_separator = "arrow"
    statusline_inactive_separator = "nil"
    enable_statusline_bfpath = true
    enable_statusline_mode = true
    enable_tabline_ft_icon = true
    enable_os_fileformat_icon = true
    buffer_index_type = 0
    windows_index_type = 2
    statusline_left_sections = ['winnr', 'version control info', 'major mode']
    statusline_right_sections = ['fileformat', 'cursorpos', 'percentage']

    # FileManager配置
    filemanager = "defx"
    enable_vimfiler_filetypeicon = true
    enable_vimfiler_gitstatus = true

    # SpaceVim配置
    enable_insert_leader = false
    windows_smartclose = ''
    windows_leader = ''
    disabled_plugins = ["vim-expand-region", "vim-table-mod", "vim-easyoperator-line", "editorconfig-vim",  "vim-choosewin"]

########################### 用户插件 ###########################
[[custom_plugins]]
    name = "mbbill/undotree"
    on_cmd = "UndotreeToggle"
    merged = false

[[custom_plugins]]
    name = "jiangmiao/auto-pairs"
    merged = false

[[custom_plugins]]
    name = "sgur/vim-textobj-parameter"
    merged = false

[[custom_plugins]]
    name = "kana/vim-textobj-function"
    merged = false

[[custom_plugins]]
    name = "octol/vim-cpp-enhanced-highlight"
    merged = false

[[custom_plugins]]
    name = "SirVer/ultisnips"
    on_ft = ["c", "cpp"]
    merged = false

[[custom_plugins]]
    name = "Shougo/echodoc.vim"
    on_ft = ["c", "cpp"]
    merged = false

[[custom_plugins]]
    name = "dense-analysis/ale"
    on_ft = ["c", "cpp"]
    merged = false

########################### 启用模块 ###########################
[[layers]]
    name = 'tools'

[[layers]]
    name = 'colorscheme'

[[layers]]
    name = 'leaderf'

[[layers]]
    name = 'git'

[[layers]]
  name = "VersionControl"

########################### 禁用模块 ###########################
[[layers]]
    name = 'shell'
    enable = false

[[layers]]
    name = 'autocomplete'
    enable = false

[[layers]]
    name = "checkers"
    enable = false

[[layers]]
    name = 'format'
    enable = false

